/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as clerk from "../clerk.js";
import type * as emails_NewSubmission from "../emails/NewSubmission.js";
import type * as emails_WelcomeEmail from "../emails/WelcomeEmail.js";
import type * as emails from "../emails.js";
import type * as forms from "../forms.js";
import type * as http from "../http.js";
import type * as stripe from "../stripe.js";
import type * as submissions from "../submissions.js";
import type * as users from "../users.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  clerk: typeof clerk;
  "emails/NewSubmission": typeof emails_NewSubmission;
  "emails/WelcomeEmail": typeof emails_WelcomeEmail;
  emails: typeof emails;
  forms: typeof forms;
  http: typeof http;
  stripe: typeof stripe;
  submissions: typeof submissions;
  users: typeof users;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
